docs(lke): metrics server install guide extra args
`extraArgs` [is a list of strings](https://github.com/bitnami/charts/blob/69cdea18b67af6c821035f998a308d8c0d2fcc34/bitnami/metrics-server/values.yaml#L179-L181) which means it fails to actually install the helm chart.

```
coalesce.go:175: warning: skipped value for metrics-server.extraArgs: Not a table.
coalesce.go:175: warning: skipped value for metrics-server.extraArgs: Not a table.
Error: YAML parse error on metrics-server/templates/deployment.yaml: error converting YAML to JSON: yaml: line 55: did not find expected '-' indicator
```

This change fixes the docs so the metrics server is correctly installed with the desired parameters.