Error creating a Linode DomainRecord: [400] [target] Invalid IPv4 or IPv6 address
Applying the provided configuration the above error occurs. Here is an output:

```
% terraform apply -var-file="secrets.tfvars" -var-file="terraform.tfvars"

An execution plan has been generated and is shown below.
...
linode_instance.my_wordpress_linode: Still creating... [30s elapsed]
linode_instance.my_wordpress_linode: Creation complete after 38s [id=18440296]

Error: Error creating a Linode DomainRecord: [400] [target] Invalid IPv4 or IPv6 address
  on main.tf line 40, in resource "linode_domain_record" "my_wordpress_domain_www_record":
  40: resource "linode_domain_record" "my_wordpress_domain_www_record" {
Error: Error creating a Linode DomainRecord: [400] [target] Invalid IPv4 or IPv6 address
  on main.tf line 47, in resource "linode_domain_record" "my_wordpress_domain_apex_record":
  47: resource "linode_domain_record" "my_wordpress_domain_apex_record" {
```

It seems it is due to not interpolation of the values in quotes ("linode_instance.my_wordpress_linode.ipv4"). If we remove quotes then incorrect attribute value type error appears:

```
Error: Incorrect attribute value type
  on main.tf line 44, in resource "linode_domain_record" "my_wordpress_domain_www_record":
  44:     target = linode_instance.my_wordpress_linode.ipv4
Inappropriate value for attribute "target": string required.
```

This is due to the fact that "ipv4" attribute of resource linode_instance is of type schema.TypeSet, but "target" attribute of resource linode_domain_record is of type schema.TypeString. And starting from Terraform 0.12 and later we need to pass a set value to tolist() function to convert it to a list value and then access list elements with element() function. The following should work: `target  = element(tolist(linode_instance.linode01.ipv4), 1)`

See the following for the references:
* https://github.com/terraform-providers/terraform-provider-linode/blob/master/linode/resource_linode_instance.go
* https://github.com/terraform-providers/terraform-provider-linode/blob/master/linode/resource_linode_domain_record.go
* https://www.terraform.io/docs/configuration/functions/tolist.html

PS: We can also use "ip_address" attribute of resource linode_instance instead of "ipv4" as it is of type TypeString and is "Linode's Public IPv4 Address. If there are multiple public IPv4 addresses on this Instance, an arbitrary address will be used for this field."